- name : creating a file in webservers
  hosts: all
  become: yes

  tasks:
    - name: creating a file
      file:
        path:  /home/ubuntu/qwe.txt
        state:  touch

    - name: using command module
      command:
        cmd: "ls"
