-  name: creating a full fledged playbook
   hosts: all
   become: yes

   handlers:
     - name : starting httpd in centos
       service:
         name: httpd
         state: started
       when: ansible_distribution=="CentOS"
        
    tasks: 
     - name: installing apache2 in ununtu machine
       apt:
         name: apache2
         state: present
       when: ansible_distribution=="Ubuntu"

     - name: installing httpd in centos7 machine
       yum:
         name : httpd
         state: present 
       when: ansible_distribution=="CentOS"
       notify:
         - starting httpd in centos


      - name: transfering the files 
        template:
          src: /home/ubuntu/test.j2
          dest: /var/www/html/test.html

