- name: creating playbooks using conditions
  hosts: webserverss
  become: yes

  tasks:
    - name: installing httpd in centos
      yum:
        name: httpd
        state: "present"
      when: ansible_distribution == "CentOS"

    - name: installing apache2 in ubuntu
      apt:
        name: apache2
        update_cache: true
        state: "latest"
      when: ansible_distribution=="Ubuntu"

    
