- name: creating playbooks using conditions
  hosts: webserverss
  become: yes

  tasks:
    - name: installing apache2 in ubuntu
      apt:
        name: apache2
        update_cache: true
        state: "latest"
      when: ansible_distribution=="Ubuntu"

    - name: installing httpd in centos
      apt:
        name: httpd
        state: "latest"
      when: ansible_distribution=="CentOs"
